config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:create, :new]
  resources :advertisings, except: [:show]

  root 'rooms#index'
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

end

app/models/advertising.rb
class Advertising
  include Mongoid::Document
  extend Refile::Mongoid::Attachment

  field :name,        type: String
  field :description, type: String
  field :address,     type: String
  field :price,       type: Float
  #field :user_ud,     type: Integer

  belongs_to :user

  attachment :image_preview, type: :image

  field :location, type: Array
  index(
    { location: '2d' }, { min: -200, max: 200 }
  )

  validates :name, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 10, less_than_or_equal_to: 1000}

  validate :check_location


  def as_json()
    json = {
      "type": "Ad",
      "id": id.to_s,
      "geometry": {
        "type": "Point",
        "coordinates": [location[0], location[1]]
      },
      "properties": {
        "name": name,
        "description": description.truncate(120),
        "price": price,
        "image_url": Refile.attachment_url(self, :image_preview, :fill, 32, 32, format: "jpg"),
        "hintContent": name
      }
    }
  end

  def self.json_for_yandex_map(collection)
    {
      "type": "FeatureCollection",
      "features": collection.as_json
    }.to_json
  end

  private

  def check_location
    if location.blank?
      self.errors.add(:address, "У данного адреса не определяются координаты")
      false
    else
      true
    end
  end

end

app/controllers/advertisings_controller.rb
class AdvertisingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_login, except: [:index]
  before_action :load_advertising,  only: [:edit, :update, :destroy]


  def index
    @from_yandex_map = params[:from] == "yandex_map"

    @advertisings = if @from_yandex_map
      Advertising.where("location" => {"$within" => {"$box" => coordinates}})
    else
      Advertising.page(params[:page]).per(5).where("location" => {"$within" => {"$box" => coordinates}})
    end
    if params[:min_price] && params[:max_price]
      @advertisings = @advertisings.where(:"price" => { :"$lte" => params[:max_price].to_f, :"$gte" => params[:min_price].to_f })
    end
    @advertisings.entries
  end

  def new
    @advertising = Advertising.new
  end

  def create
    @advertising = current_user.advertisings.new(advertising_params)
    if @advertising.save
      flash[:success] = 'объявление удачно создано'
      redirect_to edit_advertising_path(@advertising)
    else
      flash.now[:error] = 'объявление не создано'
      render :new
    end
  end

  def update
    @advertising.update(advertising_params)
    if @advertising.save
      flash[:success] = 'объявление удачно изменено'
      render :edit
    else
      flash.now[:error] = 'объявление не изменено'
      render :edit
    end
  end

  def edit
  end

  def destroy
    @advertising.destroy
    redirect_to root_path
  end

private

  def load_advertising
    @advertising = current_user.advertisings.where(id: params[:id]).first
    unless @advertising
      redirect_to root_path, flash: {error: "Ваше объявление не найдено"}
    end
  end

  def advertising_params
    params.require(:advertising).permit(:name, :description, :address, :price, :location, :image_preview).tap do |a|
      if a[:location].present?
        a[:location] = a[:location].split(' ').map(&:to_f)
      else
        a[:location] = nil
      end
    end
  end

  def coordinates
    begin
      c = params[:bbox].split(',').map(&:to_f)
      [ [c[0], c[1]],[c[2], c[3]] ]
    rescue
      [[55.44081385404796,36.769773301146316],[56.04659110740895,38.74181919958385]] #москва
    end
  end
end

app/views/advertisings/_advertising_item.html.haml
.bs-callout.bs-callout-primary.js-advertising-item{data: {object_id: advertising_item.id}}
  .row
    .col-sm-8
      %h4.name=advertising_item.name
      .price
        Цена:
        =advertising_item.price
      .description=advertising_item.description

      -if current_user && current_user == advertising_item.user
        =link_to edit_advertising_path(advertising_item) do
          %span.glyphicon.glyphicon-edit
    .col-sm-4
      = image_tag attachment_url(advertising_item, :image_preview, :fill, 100, 100, format: "jpg")

app/views/advertisings/_advertisings_list.html.haml
= render( partial: "advertising_item", collection: @advertisings)
= paginate @advertisings, remote: true

app/views/advertisings/_form.html.haml
= simple_form_for @advertising do |f|
  = f.input :name
  = f.input :price
  = f.input :description, as: :text
  = f.input :location, as: :hidden
  = f.input :image_preview, as: :file
  = f.input :address, class: "typeahead"
  = f.button :submit, "Сохранить"

:javascript
  $(document).ready(function(){
    initSearchAddress()
  });

app/views/advertisings/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 Редактирование объявление
    = render 'form'
    = link_to 'Delete', advertising_path(@advertising), :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-danger'

app/views/advertisings/index.js.haml
- if @from_yandex_map
  set_ads_to_map(#{raw Advertising.json_for_yandex_map(@advertisings)});
- else
  $('.advertisings-list').html("#{escape_javascript( render( partial: "advertisings_list"))}");
  initOpenObjectBalloon();

app/views/advertisings/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 Создание объявление
    = render 'form'