config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:create, :new]
  resources :advertisings, except: [:show]

  root 'rooms#index'
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    / %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title Room

    %script{:src => "//api-maps.yandex.ru/2.1/?lang=ru_RU", :type => "text/javascript"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/")
          Ads
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            - if current_user
              %li= link_to "Создать объявление", new_advertising_path
              %li= link_to "Выйти", :logout, method: :post
            - else
              %li= link_to "Зарегистрироваться", new_user_path
              %li= link_to "Войти", :login
    .container
      = bootstrap_flash
      = yield